import '@/app/start/start.css'
import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans'
import { ThemeProvider } from '@/components/theme-provider'

export const metadata: Metadata = {
  title: 'Giovanni Cruz',
  description: 'Generated by create next project',
}

export default function StartLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className={`${GeistSans.variable} font-sans`}>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        {children}
      </ThemeProvider>
    </div>
  )
}
