import '@/app/start.css'

import type { Metadata } from 'next'
import { Inter, Bebas_Neue } from 'next/font/google'
import { ThemeProvider } from '@/components/theme-provider'

const bebasNeue = Bebas_Neue({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-display',
})

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next Project',
  description: 'Generated by create next project',
}

export default function StartLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className={`${inter.className} ${bebasNeue.variable}`}>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
        {children}
      </ThemeProvider>
    </div>
  )
}
